// app/(tenant)/profile/profileStyles.js
import { StyleSheet, Platform, StatusBar } from "react-native";

export const IS_IOS = Platform.OS === "ios";

// ─── Palette (đồng bộ toàn app) ───────────────────────────────────────────────
export const C = {
  navy: "#1e3a8a",
  blue: "#1e40af",
  blueMid: "#2563eb",
  blueLight: "#eff6ff",
  bluePale: "#dbeafe",
  sky: "#93c5fd",
  teal: "#0d9488",
  tealLight: "#f0fdfa",
  violet: "#7c3aed",
  violetLight: "#f5f3ff",
  amber: "#d97706",
  amberLight: "#fffbeb",
  red: "#dc2626",
  redLight: "#fef2f2",
  green: "#059669",
  slate50: "#f8fafc",
  slate100: "#f1f5f9",
  slate200: "#e2e8f0",
  slate400: "#94a3b8",
  slate500: "#64748b",
  slate700: "#334155",
  slate900: "#0f172a",
  white: "#ffffff",
};

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.navy },
  body: { flex: 1, backgroundColor: C.slate100 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },

  // ── Header ──
  header: {
    backgroundColor: C.navy,
    paddingTop: IS_IOS ? 4 : StatusBar.currentHeight || 0,
    paddingHorizontal: 20,
    shadowColor: C.navy,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingBottom: 16,
  },
  headerAvatarWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerAvatarText: { fontSize: 22, fontWeight: "900", color: C.white },
  headerEyebrow: {
    fontSize: 11,
    color: C.sky,
    fontWeight: "600",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: C.white,
    marginTop: 2,
    letterSpacing: 0.2,
  },
  headerSub: { fontSize: 12, color: "rgba(147,197,253,0.75)", marginTop: 2 },

  logoutBtn: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginTop: 2,
  },

  // ── Tab bar (inside header) ──
  tabBar: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 14,
    padding: 4,
    gap: 4,
    marginBottom: 0,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 11,
  },
  tabBtnActive: { backgroundColor: C.white },
  tabLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.45)",
  },

  // ── Tab content ──
  tabContent: { padding: 16, paddingBottom: 44, gap: 14 },

  // ── Section card ──
  sectionCard: {
    backgroundColor: C.white,
    borderRadius: 18,
    padding: 16,
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },
  sectionCardHead: { flexDirection: "row", alignItems: "center", gap: 12 },
  sectionCardIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionCardTitle: { fontSize: 15, fontWeight: "700", color: C.slate900 },
  sectionCardSub: { fontSize: 11, color: C.slate400, marginTop: 1 },

  divider: { height: 1, backgroundColor: C.slate100, marginHorizontal: -16 },

  // ── InfoRow (read only) ──
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 4,
  },
  infoRowIcon: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  infoRowLabel: { fontSize: 11, color: C.slate400, fontWeight: "500" },
  infoRowValue: {
    fontSize: 14,
    color: C.slate900,
    fontWeight: "600",
    marginTop: 1,
  },

  // ── EditField ──
  editField: { gap: 5 },
  editFieldHeader: { flexDirection: "row", alignItems: "center", gap: 5 },
  editFieldLabel: { fontSize: 11, fontWeight: "600", color: C.slate500 },
  editFieldInputWrap: { position: "relative" },
  editFieldInput: {
    backgroundColor: C.slate50,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: C.slate900,
    borderWidth: 1.5,
    borderColor: C.slate200,
  },
  editFieldInputPad: { paddingRight: 44 },
  eyeBtn: {
    position: "absolute",
    right: 14,
    top: 0,
    bottom: 0,
    justifyContent: "center",
  },

  // ── Buttons ──
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.blue,
    borderRadius: 14,
    paddingVertical: 15,
    shadowColor: C.blue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 5,
  },
  primaryBtnText: { color: C.white, fontWeight: "700", fontSize: 15 },

  dangerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.red,
    borderRadius: 14,
    paddingVertical: 15,
    shadowColor: C.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  dangerBtnText: { color: C.white, fontWeight: "700", fontSize: 15 },

  successBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.violet,
    borderRadius: 14,
    paddingVertical: 15,
    shadowColor: C.violet,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  successBtnText: { color: C.white, fontWeight: "700", fontSize: 15 },

  actionRow: { flexDirection: "row", gap: 10 },
  cancelBtn: {
    flex: 1,
    backgroundColor: C.slate100,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.slate200,
  },
  cancelBtnText: { color: C.slate500, fontWeight: "700", fontSize: 14 },
  saveBtn: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.blue,
    borderRadius: 12,
    paddingVertical: 14,
    shadowColor: C.blue,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  saveBtnText: { color: C.white, fontWeight: "700", fontSize: 14 },

  // ── Vehicle ──
  vehicleBanner: {
    backgroundColor: C.navy,
    borderRadius: 18,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    overflow: "hidden",
    shadowColor: C.navy,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  vehicleBannerLeft: { gap: 2 },
  vehicleBannerNum: {
    fontSize: 52,
    fontWeight: "900",
    color: C.white,
    lineHeight: 58,
  },
  vehicleBannerLabel: { fontSize: 14, color: C.bluePale, fontWeight: "600" },

  vehicleList: { gap: 10 },
  vehicleCard: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    overflow: "hidden",
  },
  vehicleAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: 4,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    backgroundColor: C.navy,
  },
  vehicleIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  vehiclePlate: {
    fontSize: 15,
    fontWeight: "800",
    color: C.slate900,
    letterSpacing: 0.5,
  },
  vehicleBrand: { fontSize: 12, color: C.slate400, marginTop: 2 },

  vehicleEditBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.blue,
  },
  vehicleDeleteBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.red,
  },

  addVehicleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.white,
    borderRadius: 14,
    paddingVertical: 15,
    borderWidth: 2,
    borderColor: C.navy,
    borderStyle: "dashed",
  },
  addVehicleBtnText: { color: C.navy, fontWeight: "700", fontSize: 14 },

  // ── Empty state ──
  emptyWrap: { alignItems: "center", paddingVertical: 48, gap: 12 },
  emptyIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: { fontSize: 16, fontWeight: "700", color: C.slate700 },
  emptySub: {
    fontSize: 13,
    color: C.slate400,
    textAlign: "center",
    lineHeight: 19,
  },

  // ── Password tips ──
  tipCard: {
    backgroundColor: C.blueLight,
    borderRadius: 14,
    padding: 16,
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    borderLeftWidth: 3,
    borderLeftColor: C.navy,
  },
  tipTitle: { fontSize: 13, fontWeight: "700", color: C.navy, marginBottom: 4 },
  tipItem: { fontSize: 12, color: C.blue, lineHeight: 18 },

  // ── Modal sheet ──
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: C.white,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: 24,
    gap: 14,
    paddingBottom: IS_IOS ? 40 : 28,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    backgroundColor: C.slate200,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 6,
  },
  sheetTitle: { fontSize: 18, fontWeight: "800", color: C.slate900 },
});
